language: c  # without this, ruby madness kicks in.

services:
  - docker

#cache:
#  directories:
#    - $HOME/.travis_cache

before_script:
#  - ./scripts/docker-run.sh --populate-cache  # (see implementation of this flag in the script for details.)
  - grep '\(MemTotal\|SwapTotal\)' /proc/meminfo
  - git status
  - git show | head -1  # (for PR, this is the commit under test *merged into target branch*;
                        # click on the commit in travis stats for details.)

script:
  - ./scripts/docker-run.sh --test

#notifications:
#    email: false
#    irc:
#        channels:
#            - "irc.freenode.net#react-hs"
#        template: "%{branch}/%{author}: %{message}"
#        on_pull_requests: true
